version: "3"
services:
  emr-service:
    image: omrsregrepo/bahmni_092_emr:20052021
    restart: unless-stopped 
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /development_emr:/development
    command: [/usr/sbin/init, /bin/bash, "--privileged"]
    ports:
      - "443:443" #https
      - "80:80" #http
      - "8000:8000"
      - "33062:3306"
      - "8050:8050" #openmrs ws and rest api live here
    networks:
      hmis_network:
        ipv4_address: 172.27.0.3

  erp-service:
    image: omrsregrepo/bahmni_092_erp:20052021                                                                                                                                                                                                                                                                  
    privileged: true
    restart: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /development_erp:/development
    command: [/usr/sbin/init, /bin/bash, "--privileged"]
    ports:
      - "8069:8069" #odoo lives here
    networks:
      hmis_network:
        ipv4_address: 172.27.0.2
    restart: unless-stopped

networks:
  hmis_network:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
