apiVersion: apps/v1
kind: Deployment
metadata:
  name: eregister-erp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: erp
  template:
    metadata:
      labels:
        component: erp
    spec:
      containers:
        - name: eregister-erp
          image: omrsregrepo/bahmni_092_erp:18012021
          securityContext:
            privileged: true
          command: [/usr/sbin/init, /bin/bash, "--privileged"]
          ports:
            - containerPort: 8069
