apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emr-persistent-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      #storageClassName: my-storage-class
  selector:
    matchExpressions:
    - key: node.kubernetes.io/microk8s-worker
      operator: In
      values:
      - microk8s-worker
